set nocompatible

execute pathogen#infect()

syntax enable 
filetype on
filetype plugin on
filetype indent on
compiler ruby

set nowrap
set ruler
set number
set hlsearch
set lbr    "adds line breaks for text

"Solarized Theme
set t_Co=256
let g:solarized_termcolors=256
let g:solarized_termtrans = 1
set background=dark
colorscheme solarized

"Set Soft Tabs
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smartindent

"Code Folding
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

"Syntastic

let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=1
let g:syntastic_enable_highlighting=1
let g:syntastic_auto_loc_list=0
let g:syntastic_loc_list_height=15

let g:syntastic_mode_map = {'mode':'active',
    \ 'active_filetypes':['javascript', 'css', 'coffee', 'sass', 'yaml'],
    \ 'passive_filetypes':['make']}

let g:syntastic_javascript_checkers = ['jshint']

"ruby-runner
command! FR set filetype=ruby

"Mappings 
noremap .c :set cursorline!<CR>
noremap .nt :NERDTreeToggle<CR>
noremap .nh :nohl<CR>
noremap .w :set wrap!<CR>
noremap .p :set paste!<CR>
noremap .ntf :NERDTreeFind<CR>
