set nocompatible

execute pathogen#infect()

syntax enable 
filetype on
filetype plugin on
filetype indent on
compiler ruby

set nowrap
set ruler
set number
set hlsearch

"Solarized Theme
set t_Co=256
let g:solarized_termcolors=256
let g:solarized_termtrans = 1
set background=dark
colorscheme solarized

"Set Soft Tabs
set expandtab
set tabstop=2
set shiftwidth=2

"Code Folding
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

"ruby-runner
command! FR set filetype=ruby

"Mappings 
noremap .c :set cursorline!<CR>
noremap .nt :NERDTreeToggle<CR>
noremap .nh :nohl<CR>
